//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__shape__21.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__shape__21(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // Onnx__AttributeProto *a_end = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"end");
    // Onnx__AttributeProto *a_start = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"start");

    // TRACE_ATTRIBUTE(2, a_end, a_end);
    // TRACE_ATTRIBUTE(2, a_start, a_start);

    // Onnx__TensorProto *o_shape = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx__shape__21 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__shape__21));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_VAR(2, true, op_ctx->end, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->start, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_shape);

    // TRACE_TENSOR(2, true, o_shape);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__shape__21(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}