//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__slice__11.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__slice__11(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T = 0;
if (ctx->inputs[0]) {
    T = ctx->inputs[0]->data_type;
}
uint32_t Tind = 0;
if (ctx->inputs[1]) {
    Tind = ctx->inputs[1]->data_type;
}
    switch ( T ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_bool__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_bool__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX128: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_complex128__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_complex128__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX64: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_complex64__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_complex64__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_double__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_double__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_float__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_float__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_float16__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_float16__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT16: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int16__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int16__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int32__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int32__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int64__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int64__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int8__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_int8__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__STRING: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_string__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_string__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT16: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint16__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint16__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT32: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint32__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint32__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT64: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint64__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint64__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { switch ( Tind ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint8__Tind_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__slice__11__T_tensor_uint8__Tind_tensor_int64; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'Tind' with type '%s' found!\n",operator_info_tensorType2str(Tind));
        break;
    }
} break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__slice__11 and constraint 'T' with type '%s' found!\n",operator_info_tensorType2str(T));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}