//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__gridsample__22.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__gridsample__22(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_grid = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_grid);

    // Onnx__AttributeProto *a_align_corners = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"align_corners");
    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_padding_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"padding_mode");

    // TRACE_ATTRIBUTE(2, a_align_corners, a_align_corners);
    // TRACE_ATTRIBUTE(2, a_mode, a_mode);
    // TRACE_ATTRIBUTE(2, a_padding_mode, a_padding_mode);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__gridsample__22 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->align_corners, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->padding_mode, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);

    TRACE_EXIT(1);
}