//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__pad__1;
extern operator_set_opversion opversion_operator__ai_onnx__pad__2;
extern operator_set_opversion opversion_operator__ai_onnx__pad__11;
extern operator_set_opversion opversion_operator__ai_onnx__pad__13;
extern operator_set_opversion opversion_operator__ai_onnx__pad__18;
extern operator_set_opversion opversion_operator__ai_onnx__pad__19;
extern operator_set_opversion opversion_operator__ai_onnx__pad__21;

operator_set_opname opname_operator__ai_onnx__pad = {
    .name = "Pad",
    .opversions = {
        &opversion_operator__ai_onnx__pad__1,
        &opversion_operator__ai_onnx__pad__2,
        &opversion_operator__ai_onnx__pad__11,
        &opversion_operator__ai_onnx__pad__13,
        &opversion_operator__ai_onnx__pad__18,
        &opversion_operator__ai_onnx__pad__19,
        &opversion_operator__ai_onnx__pad__21,
        NULL
    }
};