//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__maxunpool__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__maxunpool__9__T1_tensor_float__T2_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_I = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_output_shape = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_I);
    // TRACE_TENSOR(2, output_shape, i_output_shape);

    // context_operator__ai_onnx__maxunpool__9 *op_ctx = ctx->executer_context;

    

    TRACE_ARRAY(2, true, kernel_shape, , n_kernel_shape, "%" PRId64);
    TRACE_ARRAY(2, true, pads, , n_pads, "%" PRId64);
    TRACE_ARRAY(2, true, strides, , n_strides, "%" PRId64);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}