//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__relu__1;
extern operator_set_opversion opversion_operator__ai_onnx__relu__6;
extern operator_set_opversion opversion_operator__ai_onnx__relu__13;
extern operator_set_opversion opversion_operator__ai_onnx__relu__14;

operator_set_opname opname_operator__ai_onnx__relu = {
    .name = "Relu",
    .opversions = {
        &opversion_operator__ai_onnx__relu__1,
        &opversion_operator__ai_onnx__relu__6,
        &opversion_operator__ai_onnx__relu__13,
        &opversion_operator__ai_onnx__relu__14,
        NULL
    }
};