//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__resize__11.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__resize__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_roi = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_scales = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_sizes = searchInputByName(ctx, 3);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_roi);
    // TRACE_TENSOR(2, true, i_scales);
    // TRACE_TENSOR(2, sizes, i_sizes);

    // Onnx__AttributeProto *a_coordinate_transformation_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"coordinate_transformation_mode");
    // Onnx__AttributeProto *a_cubic_coeff_a = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"cubic_coeff_a");
    // Onnx__AttributeProto *a_exclude_outside = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"exclude_outside");
    // Onnx__AttributeProto *a_extrapolation_value = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"extrapolation_value");
    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");
    // Onnx__AttributeProto *a_nearest_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nearest_mode");

    // TRACE_ATTRIBUTE(2, a_coordinate_transformation_mode, a_coordinate_transformation_mode);
    // TRACE_ATTRIBUTE(2, a_cubic_coeff_a, a_cubic_coeff_a);
    // TRACE_ATTRIBUTE(2, a_exclude_outside, a_exclude_outside);
    // TRACE_ATTRIBUTE(2, a_extrapolation_value, a_extrapolation_value);
    // TRACE_ATTRIBUTE(2, a_mode, a_mode);
    // TRACE_ATTRIBUTE(2, a_nearest_mode, a_nearest_mode);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__resize__11 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->coordinate_transformation_mode, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->cubic_coeff_a, "%f");
    TRACE_VAR(2, true, op_ctx->exclude_outside, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->extrapolation_value, "%f");
    TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->nearest_mode, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);

    TRACE_EXIT(1);
}