//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__dropout__6.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__dropout__6(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // Onnx__AttributeProto *a_is_test = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"is_test");
    // Onnx__AttributeProto *a_ratio = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ratio");

    // TRACE_ATTRIBUTE(2, a_is_test, a_is_test);
    // TRACE_ATTRIBUTE(2, a_ratio, a_ratio);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_mask = searchOutputByName(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx__dropout__6 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__dropout__6));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_VAR(2, true, op_ctx->is_test, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->ratio, "%f");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_output);
    // mallocTensorData(o_mask);

    // TRACE_TENSOR(2, true, o_output);
    // TRACE_TENSOR(2, mask, o_mask);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__dropout__6(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}