//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__reducel1__1;
extern operator_set_opversion opversion_operator__ai_onnx__reducel1__11;
extern operator_set_opversion opversion_operator__ai_onnx__reducel1__13;
extern operator_set_opversion opversion_operator__ai_onnx__reducel1__18;

operator_set_opname opname_operator__ai_onnx__reducel1 = {
    .name = "ReduceL1",
    .opversions = {
        &opversion_operator__ai_onnx__reducel1__1,
        &opversion_operator__ai_onnx__reducel1__11,
        &opversion_operator__ai_onnx__reducel1__13,
        &opversion_operator__ai_onnx__reducel1__18,
        NULL
    }
};