//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__pad__18.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__pad__18(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_pads = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_constant_value = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_axes = searchInputByName(ctx, 3);

    // TRACE_TENSOR(2, true, i_data);
    // TRACE_TENSOR(2, true, i_pads);
    // TRACE_TENSOR(2, constant_value, i_constant_value);
    // TRACE_TENSOR(2, axes, i_axes);

    // Onnx__AttributeProto *a_mode = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"mode");

    // TRACE_ATTRIBUTE(2, a_mode, a_mode);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__pad__18 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->mode, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_output);
    // free(o_output->dims);

    TRACE_EXIT(1);
}