//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx_preview_training__adam__1;

operator_set_opname opname_operator__ai_onnx_preview_training__adam = {
    .name = "Adam",
    .opversions = {
        &opversion_operator__ai_onnx_preview_training__adam__1,
        NULL
    }
};