//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__neg__1;
extern operator_set_opversion opversion_operator__ai_onnx__neg__6;
extern operator_set_opversion opversion_operator__ai_onnx__neg__13;

operator_set_opname opname_operator__ai_onnx__neg = {
    .name = "Neg",
    .opversions = {
        &opversion_operator__ai_onnx__neg__1,
        &opversion_operator__ai_onnx__neg__6,
        &opversion_operator__ai_onnx__neg__13,
        NULL
    }
};