//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorInfo.py
#include "operators/operator_info.h"
#include "operator__ai_onnx__maxunpool__22.h"

/* attributes */
static
operator_info_attribute
attributes[] = {
{
    .name     = "kernel_shape",
    .optional = false,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
},
{
    .name     = "pads",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
},
{
    .name     = "strides",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
}
};

/* input tensors */
static
uint32_t
input_tensor_type_X[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16,
ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
};

static
uint32_t
input_tensor_type_I[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT64
};

static
uint32_t
input_tensor_type_output_shape[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT64
};

static
operator_info_tensor
inputs[] = {
{
    .name        = "X",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 4,
    .types       = input_tensor_type_X
},
{
    .name        = "I",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 1,
    .types       = input_tensor_type_I
},
{
    .name        = "output_shape",
    .optional    = true,
    .variadic    = true,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 1,
    .types       = input_tensor_type_output_shape
}
};

/* output tensors */
static
uint32_t
output_tensor_type_output[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16,
ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
};

static
operator_info_tensor
outputs[] = {
{
    .name        = "output",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 4,
    .types       = output_tensor_type_output
}
};

/* constraints */
static
operator_info_constraint
constraints[] = {
{ "T1" },
{ "T2" }
};

/* operator info */
operator_info
info_operator__ai_onnx__maxunpool__22 = {
    .name         = "MaxUnpool",
    .range_input  = { 2, 3 },
    .range_output = { 1, 1 },
    .n_attribute  = 3,
    .attribute    = attributes,
    .n_input      = 3,
    .input        = inputs,
    .n_output     = 1,
    .output       = outputs,
    .n_constraint = 2,
    .constraint   = constraints
};