//this file was generated by ../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opdomain opdomain_operator__ai_onnx_preview_training;
extern operator_set_opdomain opdomain_operator__ai_onnx_ml;
extern operator_set_opdomain opdomain_operator__ai_onnx;

operator_set_opdomain *operator_set[] = {
        &opdomain_operator__ai_onnx_preview_training,
        &opdomain_operator__ai_onnx_ml,
        &opdomain_operator__ai_onnx,
        NULL
};