//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__constantofshape__9;
extern operator_set_opversion opversion_operator__ai_onnx__constantofshape__20;
extern operator_set_opversion opversion_operator__ai_onnx__constantofshape__21;

operator_set_opname opname_operator__ai_onnx__constantofshape = {
    .name = "ConstantOfShape",
    .opversions = {
        &opversion_operator__ai_onnx__constantofshape__9,
        &opversion_operator__ai_onnx__constantofshape__20,
        &opversion_operator__ai_onnx__constantofshape__21,
        NULL
    }
};