//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__layernormalization__17.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__layernormalization__17(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_Scale = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_Scale);
    // TRACE_TENSOR(2, B, i_B);

    // Onnx__AttributeProto *a_axis = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"axis");
    // Onnx__AttributeProto *a_epsilon = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"epsilon");
    // Onnx__AttributeProto *a_stash_type = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"stash_type");

    // TRACE_ATTRIBUTE(2, a_axis, a_axis);
    // TRACE_ATTRIBUTE(2, a_epsilon, a_epsilon);
    // TRACE_ATTRIBUTE(2, a_stash_type, a_stash_type);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Mean = searchOutputByName(ctx, 1);
    // Onnx__TensorProto *o_InvStdDev = searchOutputByName(ctx, 2);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, Mean, o_Mean);
    // TRACE_TENSOR(2, InvStdDev, o_InvStdDev);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__layernormalization__17 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->axis, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->epsilon, "%f");
    TRACE_VAR(2, true, op_ctx->stash_type, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);
    // freeTensorData(o_Mean);
    // free(o_Mean->dims);
    // freeTensorData(o_InvStdDev);
    // free(o_InvStdDev->dims);

    TRACE_EXIT(1);
}