//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__lppool__18.h"

operator_set_opversion opversion_operator__ai_onnx__lppool__18 = {
    .version  = 18,
    .preparer = prepare_operator__ai_onnx__lppool__18,
    .info = &info_operator__ai_onnx__lppool__18
};