//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx_ml__labelencoder__2.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx_ml__labelencoder__2(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T1 = 0;
if (ctx->inputs[0]) {
    T1 = ctx->inputs[0]->data_type;
}
    switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx_ml__labelencoder__2__T1_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx_ml__labelencoder__2__T1_tensor_int64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__STRING: { executer = (operator_executer) &execute_operator__ai_onnx_ml__labelencoder__2__T1_tensor_string; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx_ml__labelencoder__2 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}