//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__dft__20.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__dft__20(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_input = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_dft_length = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_axis = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_input);
    // TRACE_TENSOR(2, dft_length, i_dft_length);
    // TRACE_TENSOR(2, axis, i_axis);

    // Onnx__AttributeProto *a_inverse = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"inverse");
    // Onnx__AttributeProto *a_onesided = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"onesided");

    // TRACE_ATTRIBUTE(2, a_inverse, a_inverse);
    // TRACE_ATTRIBUTE(2, a_onesided, a_onesided);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx__dft__20 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__dft__20));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_VAR(2, true, op_ctx->inverse, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->onesided, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_output);

    // TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__dft__20(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}