//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__atanh__9;
extern operator_set_opversion opversion_operator__ai_onnx__atanh__22;

operator_set_opname opname_operator__ai_onnx__atanh = {
    .name = "Atanh",
    .opversions = {
        &opversion_operator__ai_onnx__atanh__9,
        &opversion_operator__ai_onnx__atanh__22,
        NULL
    }
};