//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__cumsum__14.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__cumsum__14__T_tensor_bfloat16__T2_tensor_int32(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_x = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_axis = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_x);
    // TRACE_TENSOR(2, true, i_axis);

    // context_operator__ai_onnx__cumsum__14 *op_ctx = ctx->executer_context;

    

    TRACE_VAR(2, true, exclusive, "%" PRId64);
    TRACE_VAR(2, true, reverse, "%" PRId64);

    // Onnx__TensorProto *o_y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}