//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__log__1;
extern operator_set_opversion opversion_operator__ai_onnx__log__6;
extern operator_set_opversion opversion_operator__ai_onnx__log__13;

operator_set_opname opname_operator__ai_onnx__log = {
    .name = "Log",
    .opversions = {
        &opversion_operator__ai_onnx__log__1,
        &opversion_operator__ai_onnx__log__6,
        &opversion_operator__ai_onnx__log__13,
        NULL
    }
};