//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__matmulinteger__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__matmulinteger__10__T1_tensor_int8__T2_tensor_int8(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_a_zero_point = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_b_zero_point = searchInputByName(ctx, 3);

    // TRACE_TENSOR(2, true, i_A);
    // TRACE_TENSOR(2, true, i_B);
    // TRACE_TENSOR(2, a_zero_point, i_a_zero_point);
    // TRACE_TENSOR(2, b_zero_point, i_b_zero_point);

    // context_operator__ai_onnx__matmulinteger__10 *op_ctx = ctx->executer_context;

    

    

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}