//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__quantizelinear__19.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__quantizelinear__19(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T1 = 0;
if (ctx->inputs[0]) {
    T1 = ctx->inputs[0]->data_type;
}
uint32_t T2 = 0;
if (ctx->outputs[0]) {
    T2 = ctx->outputs[0]->data_type;
}
    switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FN: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_tensor(float8e4m3fn); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_tensor(float8e4m3fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_tensor(float8e5m2); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_tensor(float8e5m2fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_bfloat16__T2_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__quantizelinear__19 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FN: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_tensor(float8e4m3fn); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_tensor(float8e4m3fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_tensor(float8e5m2); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_tensor(float8e5m2fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float__T2_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__quantizelinear__19 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FN: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_tensor(float8e4m3fn); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_tensor(float8e4m3fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_tensor(float8e5m2); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_tensor(float8e5m2fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_float16__T2_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__quantizelinear__19 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FN: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_tensor(float8e4m3fn); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_tensor(float8e4m3fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_tensor(float8e5m2); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_tensor(float8e5m2fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__quantizelinear__19 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__quantizelinear__19 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}