//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__splittosequence__11.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__splittosequence__11__T_tensor_uint64__I_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_input = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_split = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_input);
    // TRACE_TENSOR(2, split, i_split);

    // context_operator__ai_onnx__splittosequence__11 *op_ctx = ctx->executer_context;

    

    TRACE_VAR(2, true, axis, "%" PRId64);
    TRACE_VAR(2, true, keepdims, "%" PRId64);

    // Onnx__TensorProto *o_output_sequence = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output_sequence);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}