//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_preview_training__gradient__1.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx_preview_training__gradient__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_Inputs = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // Onnx__AttributeProto *a_xs = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"xs");
    // Onnx__AttributeProto *a_y = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"y");
    // Onnx__AttributeProto *a_zs = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"zs");

    // TRACE_ATTRIBUTE(2, true, a_xs);
    // TRACE_ATTRIBUTE(2, true, a_y);
    // TRACE_ATTRIBUTE(2, a_zs, a_zs);

    // Onnx__TensorProto *o_Outputs = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Outputs);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx_preview_training__gradient__1 *op_ctx = ctx->executer_context;

    TRACE_ARRAY(2, true, op_ctx->xs, , op_ctx->n_xs, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->y, "\"%s\"");
    TRACE_ARRAY(2, true, op_ctx->zs, , op_ctx->n_zs, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Outputs);
    // free(o_Outputs->dims);

    TRACE_EXIT(1);
}