//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__qlinearmatmul__10;
extern operator_set_opversion opversion_operator__ai_onnx__qlinearmatmul__21;

operator_set_opname opname_operator__ai_onnx__qlinearmatmul = {
    .name = "QLinearMatMul",
    .opversions = {
        &opversion_operator__ai_onnx__qlinearmatmul__10,
        &opversion_operator__ai_onnx__qlinearmatmul__21,
        NULL
    }
};