//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__bernoulli__15;
extern operator_set_opversion opversion_operator__ai_onnx__bernoulli__22;

operator_set_opname opname_operator__ai_onnx__bernoulli = {
    .name = "Bernoulli",
    .opversions = {
        &opversion_operator__ai_onnx__bernoulli__15,
        &opversion_operator__ai_onnx__bernoulli__22,
        NULL
    }
};