//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__sin__7;
extern operator_set_opversion opversion_operator__ai_onnx__sin__22;

operator_set_opname opname_operator__ai_onnx__sin = {
    .name = "Sin",
    .opversions = {
        &opversion_operator__ai_onnx__sin__7,
        &opversion_operator__ai_onnx__sin__22,
        NULL
    }
};