//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorInfo.py
#include "operators/operator_info.h"
#include "operator__ai_onnx__imagedecoder__20.h"

/* attributes */
static
operator_info_attribute
attributes[] = {
{
    .name     = "pixel_format",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__STRING
}
};

/* input tensors */
static
uint32_t
input_tensor_type_encoded_stream[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
operator_info_tensor
inputs[] = {
{
    .name        = "encoded_stream",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 1,
    .types       = input_tensor_type_encoded_stream
}
};

/* output tensors */
static
uint32_t
output_tensor_type_image[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
operator_info_tensor
outputs[] = {
{
    .name        = "image",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 1,
    .types       = output_tensor_type_image
}
};

/* constraints */
static
operator_info_constraint
constraints[] = {
{ "T1" },
{ "T2" }
};

/* operator info */
operator_info
info_operator__ai_onnx__imagedecoder__20 = {
    .name         = "ImageDecoder",
    .range_input  = { 1, 1 },
    .range_output = { 1, 1 },
    .n_attribute  = 1,
    .attribute    = attributes,
    .n_input      = 1,
    .input        = inputs,
    .n_output     = 1,
    .output       = outputs,
    .n_constraint = 2,
    .constraint   = constraints
};