//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__isinf__20.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__isinf__20(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T1 = 0;
if (ctx->inputs[0]) {
    T1 = ctx->inputs[0]->data_type;
}
    switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_bfloat16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_float16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FN: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_tensor(float8e4m3fn); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E4M3FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_tensor(float8e4m3fnuz); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_tensor(float8e5m2); break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT8E5M2FNUZ: { executer = (operator_executer) &execute_operator__ai_onnx__isinf__20__T1_tensor_tensor(float8e5m2fnuz); break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__isinf__20 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}