//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx__tanh__13.h"

operator_set_opversion opversion_operator__ai_onnx__tanh__13 = {
    .version  = 13,
    .preparer = prepare_operator__ai_onnx__tanh__13,
    .info = &info_operator__ai_onnx__tanh__13
};