//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__resize__13.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__resize__13__T1_tensor_bfloat16__T2_tensor_double(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_roi = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_scales = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_sizes = searchInputByName(ctx, 3);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, roi, i_roi);
    // TRACE_TENSOR(2, scales, i_scales);
    // TRACE_TENSOR(2, sizes, i_sizes);

    // context_operator__ai_onnx__resize__13 *op_ctx = ctx->executer_context;

    

    TRACE_VAR(2, true, coordinate_transformation_mode, "\"%s\"");
    TRACE_VAR(2, true, cubic_coeff_a, "%f");
    TRACE_VAR(2, true, exclude_outside, "%" PRId64);
    TRACE_VAR(2, true, extrapolation_value, "%f");
    TRACE_VAR(2, true, mode, "\"%s\"");
    TRACE_VAR(2, true, nearest_mode, "\"%s\"");

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}