//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__cumsum__11.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__cumsum__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_x = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_axis = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_x);
    // TRACE_TENSOR(2, true, i_axis);

    // Onnx__AttributeProto *a_exclusive = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"exclusive");
    // Onnx__AttributeProto *a_reverse = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"reverse");

    // TRACE_ATTRIBUTE(2, a_exclusive, a_exclusive);
    // TRACE_ATTRIBUTE(2, a_reverse, a_reverse);

    // Onnx__TensorProto *o_y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_y);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__cumsum__11 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->exclusive, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->reverse, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_y);
    // free(o_y->dims);

    TRACE_EXIT(1);
}