//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__matmulinteger__10.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__matmulinteger__10(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_a_zero_point = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_b_zero_point = searchInputByName(ctx, 3);

    // TRACE_TENSOR(2, true, i_A);
    // TRACE_TENSOR(2, true, i_B);
    // TRACE_TENSOR(2, a_zero_point, i_a_zero_point);
    // TRACE_TENSOR(2, b_zero_point, i_b_zero_point);

    

    

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Y);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__matmulinteger__10 *op_ctx = ctx->executer_context;

    

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);

    TRACE_EXIT(1);
}