//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__cumsum__11;
extern operator_set_opversion opversion_operator__ai_onnx__cumsum__14;

operator_set_opname opname_operator__ai_onnx__cumsum = {
    .name = "CumSum",
    .opversions = {
        &opversion_operator__ai_onnx__cumsum__11,
        &opversion_operator__ai_onnx__cumsum__14,
        NULL
    }
};