//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__dequantizelinear__10;
extern operator_set_opversion opversion_operator__ai_onnx__dequantizelinear__13;
extern operator_set_opversion opversion_operator__ai_onnx__dequantizelinear__19;
extern operator_set_opversion opversion_operator__ai_onnx__dequantizelinear__21;

operator_set_opname opname_operator__ai_onnx__dequantizelinear = {
    .name = "DequantizeLinear",
    .opversions = {
        &opversion_operator__ai_onnx__dequantizelinear__10,
        &opversion_operator__ai_onnx__dequantizelinear__13,
        &opversion_operator__ai_onnx__dequantizelinear__19,
        &opversion_operator__ai_onnx__dequantizelinear__21,
        NULL
    }
};