//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__gridsample__20.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__gridsample__20(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t T1 = 0;
if (ctx->inputs[0]) {
    T1 = ctx->inputs[0]->data_type;
}
uint32_t T2 = 0;
if (ctx->inputs[1]) {
    T2 = ctx->inputs[1]->data_type;
}
    switch ( T1 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_bool__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_bool__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_bool__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX128: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex128__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex128__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex128__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX64: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex64__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex64__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_complex64__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_double__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_double__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_double__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float16__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float16__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_float16__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT16: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int16__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int16__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int16__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int32__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int32__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int32__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int64__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int64__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int64__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int8__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int8__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_int8__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__STRING: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_string__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_string__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_string__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT16: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint16__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint16__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint16__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT32: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint32__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint32__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint32__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT64: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint64__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint64__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint64__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { switch ( T2 ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint8__T2_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint8__T2_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__gridsample__20__T1_tensor_uint8__T2_tensor_float16; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T2' with type '%s' found!\n",operator_info_tensorType2str(T2));
        break;
    }
} break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__gridsample__20 and constraint 'T1' with type '%s' found!\n",operator_info_tensorType2str(T1));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}