//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__einsum__12.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__einsum__12(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_Inputs = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // Onnx__AttributeProto *a_equation = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"equation");

    // TRACE_ATTRIBUTE(2, true, a_equation);

    // Onnx__TensorProto *o_Output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_Output);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__einsum__12 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->equation, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Output);
    // free(o_Output->dims);

    TRACE_EXIT(1);
}