//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__centercroppad__18.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__centercroppad__18(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_input_data = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_shape = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, true, i_input_data);
    // TRACE_TENSOR(2, true, i_shape);

    // Onnx__AttributeProto *a_axes = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"axes");

    // TRACE_ATTRIBUTE(2, a_axes, a_axes);

    // Onnx__TensorProto *o_output_data = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output_data);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__centercroppad__18 *op_ctx = ctx->executer_context;

    TRACE_ARRAY(2, true, op_ctx->axes, , op_ctx->n_axes, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_output_data);
    // free(o_output_data->dims);

    TRACE_EXIT(1);
}