//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"
#include "operator__ai_onnx_ml__treeensembleclassifier__3.h"

operator_set_opversion opversion_operator__ai_onnx_ml__treeensembleclassifier__3 = {
    .version  = 3,
    .preparer = prepare_operator__ai_onnx_ml__treeensembleclassifier__3,
    .info = &info_operator__ai_onnx_ml__treeensembleclassifier__3
};