//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorInfo.py
#include "operators/operator_info.h"
#include "operator__ai_onnx__affinegrid__20.h"

/* attributes */
static
operator_info_attribute
attributes[] = {
{
    .name     = "align_corners",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT
}
};

/* input tensors */
static
uint32_t
input_tensor_type_theta[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16,
ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
};

static
uint32_t
input_tensor_type_size[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT64
};

static
operator_info_tensor
inputs[] = {
{
    .name        = "theta",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 4,
    .types       = input_tensor_type_theta
},
{
    .name        = "size",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 1,
    .types       = input_tensor_type_size
}
};

/* output tensors */
static
uint32_t
output_tensor_type_grid[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__BFLOAT16,
ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT,
ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16
};

static
operator_info_tensor
outputs[] = {
{
    .name        = "grid",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 4,
    .types       = output_tensor_type_grid
}
};

/* constraints */
static
operator_info_constraint
constraints[] = {
{ "T1" },
{ "T2" }
};

/* operator info */
operator_info
info_operator__ai_onnx__affinegrid__20 = {
    .name         = "AffineGrid",
    .range_input  = { 2, 2 },
    .range_output = { 1, 1 },
    .n_attribute  = 1,
    .attribute    = attributes,
    .n_input      = 2,
    .input        = inputs,
    .n_output     = 1,
    .output       = outputs,
    .n_constraint = 2,
    .constraint   = constraints
};