//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__gru__14.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__gru__14(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_W = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_R = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 3);
    // Onnx__TensorProto *i_sequence_lens = searchInputByName(ctx, 4);
    // Onnx__TensorProto *i_initial_h = searchInputByName(ctx, 5);

    // TRACE_TENSOR(2, true, i_X);
    // TRACE_TENSOR(2, true, i_W);
    // TRACE_TENSOR(2, true, i_R);
    // TRACE_TENSOR(2, B, i_B);
    // TRACE_TENSOR(2, sequence_lens, i_sequence_lens);
    // TRACE_TENSOR(2, initial_h, i_initial_h);

    // Onnx__AttributeProto *a_activation_alpha = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activation_alpha");
    // Onnx__AttributeProto *a_activation_beta = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activation_beta");
    // Onnx__AttributeProto *a_activations = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"activations");
    // Onnx__AttributeProto *a_clip = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"clip");
    // Onnx__AttributeProto *a_direction = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"direction");
    // Onnx__AttributeProto *a_hidden_size = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"hidden_size");
    // Onnx__AttributeProto *a_layout = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"layout");
    // Onnx__AttributeProto *a_linear_before_reset = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"linear_before_reset");

    // TRACE_ATTRIBUTE(2, a_activation_alpha, a_activation_alpha);
    // TRACE_ATTRIBUTE(2, a_activation_beta, a_activation_beta);
    // TRACE_ATTRIBUTE(2, a_activations, a_activations);
    // TRACE_ATTRIBUTE(2, a_clip, a_clip);
    // TRACE_ATTRIBUTE(2, a_direction, a_direction);
    // TRACE_ATTRIBUTE(2, a_hidden_size, a_hidden_size);
    // TRACE_ATTRIBUTE(2, a_layout, a_layout);
    // TRACE_ATTRIBUTE(2, a_linear_before_reset, a_linear_before_reset);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Y_h = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, Y, o_Y);
    // TRACE_TENSOR(2, Y_h, o_Y_h);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__gru__14 *op_ctx = ctx->executer_context;

    TRACE_ARRAY(2, true, op_ctx->activation_alpha, , op_ctx->n_activation_alpha, "%f");
    TRACE_ARRAY(2, true, op_ctx->activation_beta, , op_ctx->n_activation_beta, "%f");
    TRACE_ARRAY(2, true, op_ctx->activations, , op_ctx->n_activations, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->clip, "%f");
    TRACE_VAR(2, true, op_ctx->direction, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->hidden_size, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->layout, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->linear_before_reset, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_Y);
    // free(o_Y->dims);
    // freeTensorData(o_Y_h);
    // free(o_Y_h->dims);

    TRACE_EXIT(1);
}