//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__softmaxcrossentropyloss__12.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__softmaxcrossentropyloss__12(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_scores = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_labels = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_weights = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_scores);
    // TRACE_TENSOR(2, true, i_labels);
    // TRACE_TENSOR(2, weights, i_weights);

    // Onnx__AttributeProto *a_ignore_index = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"ignore_index");
    // Onnx__AttributeProto *a_reduction = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"reduction");

    // TRACE_ATTRIBUTE(2, a_ignore_index, a_ignore_index);
    // TRACE_ATTRIBUTE(2, a_reduction, a_reduction);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_log_prob = searchOutputByName(ctx, 1);

    // TRACE_TENSOR(2, true, o_output);
    // TRACE_TENSOR(2, log_prob, o_log_prob);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__softmaxcrossentropyloss__12 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->ignore_index, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->reduction, "\"%s\"");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_output);
    // free(o_output->dims);
    // freeTensorData(o_log_prob);
    // free(o_log_prob->dims);

    TRACE_EXIT(1);
}