//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_preview_training__gradient__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_preview_training__gradient__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_Inputs = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_Inputs);

    // Onnx__AttributeProto *a_xs = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"xs");
    // Onnx__AttributeProto *a_y = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"y");
    // Onnx__AttributeProto *a_zs = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"zs");

    // TRACE_ATTRIBUTE(2, true, a_xs);
    // TRACE_ATTRIBUTE(2, true, a_y);
    // TRACE_ATTRIBUTE(2, a_zs, a_zs);

    // Onnx__TensorProto *o_Outputs = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx_preview_training__gradient__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_preview_training__gradient__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_ARRAY(2, true, op_ctx->xs, , op_ctx->n_xs, "\"%s\"");
    TRACE_VAR(2, true, op_ctx->y, "\"%s\"");
    TRACE_ARRAY(2, true, op_ctx->zs, , op_ctx->n_zs, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Outputs);

    // TRACE_TENSOR(2, true, o_Outputs);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_preview_training__gradient__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}