//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__hannwindow__17;

operator_set_opname opname_operator__ai_onnx__hannwindow = {
    .name = "HannWindow",
    .opversions = {
        &opversion_operator__ai_onnx__hannwindow__17,
        NULL
    }
};