//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__round__11;
extern operator_set_opversion opversion_operator__ai_onnx__round__22;

operator_set_opname opname_operator__ai_onnx__round = {
    .name = "Round",
    .opversions = {
        &opversion_operator__ai_onnx__round__11,
        &opversion_operator__ai_onnx__round__22,
        NULL
    }
};