//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__SEQUENCEMAP__17_H
# define OPERATOR_OPERATOR__AI_ONNX__SEQUENCEMAP__17_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'SequenceMap' version 17
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * Applies a sub-graph to each sample in the input sequence(s).
 * 
 * Inputs can be either tensors or sequences, with the exception of the first input which must
 * be a sequence. The length of the first input sequence will determine the number of samples in the
 * outputs. Any other sequence inputs should have the same number of samples. The number of inputs
 * and outputs, should match the one of the subgraph.
 * 
 * For each i-th element in the output, a sample will be extracted from the input sequence(s) at
 * the i-th position and the sub-graph will be applied to it.
 * The outputs will contain the outputs of the sub-graph for each sample, in the same order as in
 * the input.
 * 
 * This operator assumes that processing each sample is independent and could executed in parallel
 * or in any order. Users cannot expect any specific ordering in which each subgraph is computed.
 * 
 * Constraint S:
 *   Constrain input types to any sequence type.
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8
 * 
 * Constraint V:
 *   Constrain to any tensor or sequence type.
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8, tensor_bool, tensor_complex128,
 *                  tensor_complex64, tensor_double, tensor_float,
 *                  tensor_float16, tensor_int16, tensor_int32, tensor_int64,
 *                  tensor_int8, tensor_string, tensor_uint16, tensor_uint32,
 *                  tensor_uint64, tensor_uint8
 * Input S input_sequence:
 *   Input sequence.
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8
 * 
 * Input V additional_inputs:
 *   Additional inputs to the graph
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8, tensor_bool, tensor_complex128,
 *                  tensor_complex64, tensor_double, tensor_float,
 *                  tensor_float16, tensor_int16, tensor_int32, tensor_int64,
 *                  tensor_int8, tensor_string, tensor_uint16, tensor_uint32,
 *                  tensor_uint64, tensor_uint8
 * Output S out_sequence:
 *   Output sequence(s)
 *   Allowed Types: seq_tensor_bool, seq_tensor_complex128,
 *                  seq_tensor_complex64, seq_tensor_double, seq_tensor_float,
 *                  seq_tensor_float16, seq_tensor_int16, seq_tensor_int32,
 *                  seq_tensor_int64, seq_tensor_int8, seq_tensor_string,
 *                  seq_tensor_uint16, seq_tensor_uint32, seq_tensor_uint64,
 *                  seq_tensor_uint8
 * Attribute GRAPH body :
 *   The graph to be run for each sample in the sequence(s). It should have as
 *   many inputs and outputs as inputs and outputs to the SequenceMap function.
 *
 * @since version 17
 *
 * @see github/workspace/onnx/defs/sequence/defs.cc:761
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#SequenceMap
 */

operator_status
prepare_operator__ai_onnx__sequencemap__17(
    node_context *ctx
);

extern operator_info info_operator__ai_onnx__sequencemap__17;

typedef struct {
// no attributes
} context_operator__ai_onnx__sequencemap__17;

operator_executer
resolve_operator__ai_onnx__sequencemap__17(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_bool__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex128__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_complex64__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_double__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_float16__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int16__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int32__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int64__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_int8__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_string__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint16__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint32__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint64__V_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_seq_tensor_uint8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_bool(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_complex128(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_complex64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_double(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_float(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_float16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_int16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_int32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_int64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_int8(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_string(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_uint16(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_uint32(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_uint64(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__sequencemap__17__S_seq_tensor_uint8__V_tensor_uint8(
    node_context *ctx
);

# endif