//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__max__1;
extern operator_set_opversion opversion_operator__ai_onnx__max__6;
extern operator_set_opversion opversion_operator__ai_onnx__max__8;
extern operator_set_opversion opversion_operator__ai_onnx__max__12;
extern operator_set_opversion opversion_operator__ai_onnx__max__13;

operator_set_opname opname_operator__ai_onnx__max = {
    .name = "Max",
    .opversions = {
        &opversion_operator__ai_onnx__max__1,
        &opversion_operator__ai_onnx__max__6,
        &opversion_operator__ai_onnx__max__8,
        &opversion_operator__ai_onnx__max__12,
        &opversion_operator__ai_onnx__max__13,
        NULL
    }
};