//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__constant__13.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__constant__13(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    

    

    // context_operator__ai_onnx__constant__13 *op_ctx = ctx->executer_context;

    

    TRACE_VAR(2, true, sparse_value, "%p");
    TRACE_TENSOR(2, true, value);
    TRACE_VAR(2, true, value_float, "%f");
    TRACE_ARRAY(2, true, value_floats, , n_value_floats, "%f");
    TRACE_VAR(2, true, value_int, "%" PRId64);
    TRACE_ARRAY(2, true, value_ints, , n_value_ints, "%" PRId64);
    TRACE_VAR(2, true, value_string, "\"%s\"");
    TRACE_ARRAY(2, true, value_strings, , n_value_strings, "\"%s\"");

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}