//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__scan__8.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__scan__8(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_sequence_lens = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_initial_state_and_scan_inputs = searchInputByName(ctx, 1);

    // TRACE_TENSOR(2, sequence_lens, i_sequence_lens);
    // TRACE_TENSOR(2, true, i_initial_state_and_scan_inputs);

    // Onnx__AttributeProto *a_body = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"body");
    // Onnx__AttributeProto *a_directions = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"directions");
    // Onnx__AttributeProto *a_num_scan_inputs = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"num_scan_inputs");

    // TRACE_ATTRIBUTE(2, true, a_body);
    // TRACE_ATTRIBUTE(2, a_directions, a_directions);
    // TRACE_ATTRIBUTE(2, true, a_num_scan_inputs);

    // Onnx__TensorProto *o_final_state_and_scan_outputs = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_final_state_and_scan_outputs);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__scan__8 *op_ctx = ctx->executer_context;

    TRACE_GRAPH(2, true, op_ctx->body);
    TRACE_ARRAY(2, true, op_ctx->directions, , op_ctx->n_directions, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->num_scan_inputs, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_final_state_and_scan_outputs);
    // free(o_final_state_and_scan_outputs->dims);

    TRACE_EXIT(1);
}