//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTypeResolver.py
#include "operator__ai_onnx__scan__8.h"
#include "operators/operator_stub.h"
#include <inttypes.h>
#include <stdio.h>

operator_executer
resolve_operator__ai_onnx__scan__8(
    node_context *ctx
){
    operator_executer executer = NULL;
    {
    uint32_t I = 0;
if (ctx->inputs[0]) {
    I = ctx->inputs[0]->data_type;
}
uint32_t V = 0;
if (ctx->inputs[1]) {
    V = ctx->inputs[1]->data_type;
}
    switch ( I ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { switch ( V ) {
    case 0: //constrained tensor is not set (maybe optional?), just take next case
    case ONNX__TENSOR_PROTO__DATA_TYPE__BOOL: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_bool; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX128: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_complex128; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__COMPLEX64: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_complex64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__DOUBLE: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_double; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_float; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__FLOAT16: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_float16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT16: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_int16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT32: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_int32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT64: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_int64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__INT8: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_int8; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__STRING: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_string; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT16: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_uint16; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT32: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_uint32; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT64: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_uint64; break; }
case ONNX__TENSOR_PROTO__DATA_TYPE__UINT8: { executer = (operator_executer) &execute_operator__ai_onnx__scan__8__I_tensor_int64__V_tensor_uint8; break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__scan__8 and constraint 'V' with type '%s' found!\n",operator_info_tensorType2str(V));
        break;
    }
} break; }
    default: {
        fprintf(stderr, "no matching type for operator__ai_onnx__scan__8 and constraint 'I' with type '%s' found!\n",operator_info_tensorType2str(I));
        break;
    }
}
}
    if (!executer) {
        executer = &operator_stub;
    }
    return executer;
}