//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorInfo.py
#include "operators/operator_info.h"
#include "operator__ai_onnx__convinteger__10.h"

/* attributes */
static
operator_info_attribute
attributes[] = {
{
    .name     = "auto_pad",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__STRING
},
{
    .name     = "dilations",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
},
{
    .name     = "group",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INT
},
{
    .name     = "kernel_shape",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
},
{
    .name     = "pads",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
},
{
    .name     = "strides",
    .optional = true,
    .type     = ONNX__ATTRIBUTE_PROTO__ATTRIBUTE_TYPE__INTS
}
};

/* input tensors */
static
uint32_t
input_tensor_type_x[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT8,
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
uint32_t
input_tensor_type_w[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT8,
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
uint32_t
input_tensor_type_x_zero_point[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT8,
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
uint32_t
input_tensor_type_w_zero_point[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT8,
ONNX__TENSOR_PROTO__DATA_TYPE__UINT8
};

static
operator_info_tensor
inputs[] = {
{
    .name        = "x",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 2,
    .types       = input_tensor_type_x
},
{
    .name        = "w",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 2,
    .types       = input_tensor_type_w
},
{
    .name        = "x_zero_point",
    .optional    = true,
    .variadic    = true,
    .homogeneous = true,
    .constraint  = "T1",
    .n_types     = 2,
    .types       = input_tensor_type_x_zero_point
},
{
    .name        = "w_zero_point",
    .optional    = true,
    .variadic    = true,
    .homogeneous = true,
    .constraint  = "T2",
    .n_types     = 2,
    .types       = input_tensor_type_w_zero_point
}
};

/* output tensors */
static
uint32_t
output_tensor_type_y[] = {
ONNX__TENSOR_PROTO__DATA_TYPE__INT32
};

static
operator_info_tensor
outputs[] = {
{
    .name        = "y",
    .optional    = false,
    .variadic    = false,
    .homogeneous = true,
    .constraint  = "T3",
    .n_types     = 1,
    .types       = output_tensor_type_y
}
};

/* constraints */
static
operator_info_constraint
constraints[] = {
{ "T1" },
{ "T2" },
{ "T3" }
};

/* operator info */
operator_info
info_operator__ai_onnx__convinteger__10 = {
    .name         = "ConvInteger",
    .range_input  = { 2, 4 },
    .range_output = { 1, 1 },
    .n_attribute  = 6,
    .attribute    = attributes,
    .n_input      = 4,
    .input        = inputs,
    .n_output     = 1,
    .output       = outputs,
    .n_constraint = 3,
    .constraint   = constraints
};