//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__shape__15.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__shape__15(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_data = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_data);

    // Onnx__AttributeProto *a_end = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"end");
    // Onnx__AttributeProto *a_start = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"start");

    // TRACE_ATTRIBUTE(2, a_end, a_end);
    // TRACE_ATTRIBUTE(2, a_start, a_start);

    // Onnx__TensorProto *o_shape = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_shape);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__shape__15 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->end, "%" PRId64);
    TRACE_VAR(2, true, op_ctx->start, "%" PRId64);

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_shape);
    // free(o_shape->dims);

    TRACE_EXIT(1);
}