//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__negativeloglikelihoodloss__12;
extern operator_set_opversion opversion_operator__ai_onnx__negativeloglikelihoodloss__13;
extern operator_set_opversion opversion_operator__ai_onnx__negativeloglikelihoodloss__22;

operator_set_opname opname_operator__ai_onnx__negativeloglikelihoodloss = {
    .name = "NegativeLogLikelihoodLoss",
    .opversions = {
        &opversion_operator__ai_onnx__negativeloglikelihoodloss__12,
        &opversion_operator__ai_onnx__negativeloglikelihoodloss__13,
        &opversion_operator__ai_onnx__negativeloglikelihoodloss__22,
        NULL
    }
};