//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__dequantizelinear__10.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__dequantizelinear__10__T_tensor_int32(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_x = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_x_scale = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_x_zero_point = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_x);
    // TRACE_TENSOR(2, true, i_x_scale);
    // TRACE_TENSOR(2, x_zero_point, i_x_zero_point);

    // context_operator__ai_onnx__dequantizelinear__10 *op_ctx = ctx->executer_context;

    

    

    // Onnx__TensorProto *o_y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}