//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__loop__13.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__loop__13__V_tensor_complex64__I_tensor_int64__B_tensor_bool(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_M = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_cond = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_v_initial = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, M, i_M);
    // TRACE_TENSOR(2, cond, i_cond);
    // TRACE_TENSOR(2, true, i_v_initial);

    // context_operator__ai_onnx__loop__13 *op_ctx = ctx->executer_context;

    

    TRACE_GRAPH(2, true, body);

    // Onnx__TensorProto *o_v_final_and_scan_outputs = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_v_final_and_scan_outputs);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}