//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__randomnormallike__1;
extern operator_set_opversion opversion_operator__ai_onnx__randomnormallike__22;

operator_set_opname opname_operator__ai_onnx__randomnormallike = {
    .name = "RandomNormalLike",
    .opversions = {
        &opversion_operator__ai_onnx__randomnormallike__1,
        &opversion_operator__ai_onnx__randomnormallike__22,
        NULL
    }
};