//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__melweightmatrix__17.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__melweightmatrix__17(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_num_mel_bins = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_dft_length = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_sample_rate = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_lower_edge_hertz = searchInputByName(ctx, 3);
    // Onnx__TensorProto *i_upper_edge_hertz = searchInputByName(ctx, 4);

    // TRACE_TENSOR(2, true, i_num_mel_bins);
    // TRACE_TENSOR(2, true, i_dft_length);
    // TRACE_TENSOR(2, true, i_sample_rate);
    // TRACE_TENSOR(2, true, i_lower_edge_hertz);
    // TRACE_TENSOR(2, true, i_upper_edge_hertz);

    // Onnx__AttributeProto *a_output_datatype = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"output_datatype");

    // TRACE_ATTRIBUTE(2, a_output_datatype, a_output_datatype);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx__melweightmatrix__17 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__melweightmatrix__17));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_VAR(2, true, op_ctx->output_datatype, "%" PRId64);

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_output);

    // TRACE_TENSOR(2, true, o_output);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx__melweightmatrix__17(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}