//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx_ml__linearclassifier__1;

operator_set_opname opname_operator__ai_onnx_ml__linearclassifier = {
    .name = "LinearClassifier",
    .opversions = {
        &opversion_operator__ai_onnx_ml__linearclassifier__1,
        NULL
    }
};