//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx_ml__treeensembleclassifier__1.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx_ml__treeensembleclassifier__1(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_X = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_X);

    // Onnx__AttributeProto *a_base_values = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"base_values");
    // Onnx__AttributeProto *a_class_ids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_ids");
    // Onnx__AttributeProto *a_class_nodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_nodeids");
    // Onnx__AttributeProto *a_class_treeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_treeids");
    // Onnx__AttributeProto *a_class_weights = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"class_weights");
    // Onnx__AttributeProto *a_classlabels_int64s = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_int64s");
    // Onnx__AttributeProto *a_classlabels_strings = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"classlabels_strings");
    // Onnx__AttributeProto *a_nodes_falsenodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_falsenodeids");
    // Onnx__AttributeProto *a_nodes_featureids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_featureids");
    // Onnx__AttributeProto *a_nodes_hitrates = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_hitrates");
    // Onnx__AttributeProto *a_nodes_missing_value_tracks_true = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_missing_value_tracks_true");
    // Onnx__AttributeProto *a_nodes_modes = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_modes");
    // Onnx__AttributeProto *a_nodes_nodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_nodeids");
    // Onnx__AttributeProto *a_nodes_treeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_treeids");
    // Onnx__AttributeProto *a_nodes_truenodeids = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_truenodeids");
    // Onnx__AttributeProto *a_nodes_values = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"nodes_values");
    // Onnx__AttributeProto *a_post_transform = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"post_transform");

    // TRACE_ATTRIBUTE(2, a_base_values, a_base_values);
    // TRACE_ATTRIBUTE(2, a_class_ids, a_class_ids);
    // TRACE_ATTRIBUTE(2, a_class_nodeids, a_class_nodeids);
    // TRACE_ATTRIBUTE(2, a_class_treeids, a_class_treeids);
    // TRACE_ATTRIBUTE(2, a_class_weights, a_class_weights);
    // TRACE_ATTRIBUTE(2, a_classlabels_int64s, a_classlabels_int64s);
    // TRACE_ATTRIBUTE(2, a_classlabels_strings, a_classlabels_strings);
    // TRACE_ATTRIBUTE(2, a_nodes_falsenodeids, a_nodes_falsenodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_featureids, a_nodes_featureids);
    // TRACE_ATTRIBUTE(2, a_nodes_hitrates, a_nodes_hitrates);
    // TRACE_ATTRIBUTE(2, a_nodes_missing_value_tracks_true, a_nodes_missing_value_tracks_true);
    // TRACE_ATTRIBUTE(2, a_nodes_modes, a_nodes_modes);
    // TRACE_ATTRIBUTE(2, a_nodes_nodeids, a_nodes_nodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_treeids, a_nodes_treeids);
    // TRACE_ATTRIBUTE(2, a_nodes_truenodeids, a_nodes_truenodeids);
    // TRACE_ATTRIBUTE(2, a_nodes_values, a_nodes_values);
    // TRACE_ATTRIBUTE(2, a_post_transform, a_post_transform);

    // Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);
    // Onnx__TensorProto *o_Z = searchOutputByName(ctx, 1);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    

    // context_operator__ai_onnx_ml__treeensembleclassifier__1 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx_ml__treeensembleclassifier__1));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    

    TRACE_ARRAY(2, true, op_ctx->base_values, , op_ctx->n_base_values, "%f");
    TRACE_ARRAY(2, true, op_ctx->class_ids, , op_ctx->n_class_ids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->class_nodeids, , op_ctx->n_class_nodeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->class_treeids, , op_ctx->n_class_treeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->class_weights, , op_ctx->n_class_weights, "%f");
    TRACE_ARRAY(2, true, op_ctx->classlabels_int64s, , op_ctx->n_classlabels_int64s, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->classlabels_strings, , op_ctx->n_classlabels_strings, "\"%s\"");
    TRACE_ARRAY(2, true, op_ctx->nodes_falsenodeids, , op_ctx->n_nodes_falsenodeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_featureids, , op_ctx->n_nodes_featureids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_hitrates, , op_ctx->n_nodes_hitrates, "%f");
    TRACE_ARRAY(2, true, op_ctx->nodes_missing_value_tracks_true, , op_ctx->n_nodes_missing_value_tracks_true, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_modes, , op_ctx->n_nodes_modes, "\"%s\"");
    TRACE_ARRAY(2, true, op_ctx->nodes_nodeids, , op_ctx->n_nodes_nodeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_treeids, , op_ctx->n_nodes_treeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_truenodeids, , op_ctx->n_nodes_truenodeids, "%" PRId64);
    TRACE_ARRAY(2, true, op_ctx->nodes_values, , op_ctx->n_nodes_values, "%f");
    TRACE_VAR(2, true, op_ctx->post_transform, "\"%s\"");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */


    /* MALLOC OUTPUT TENSORS HERE */

    // mallocTensorData(o_Y);
    // mallocTensorData(o_Z);

    // TRACE_TENSOR(2, true, o_Y);
    // TRACE_TENSOR(2, true, o_Z);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    // ctx->executer = resolve_operator__ai_onnx_ml__treeensembleclassifier__1(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}