//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx_ml__treeensembleregressor__1;
extern operator_set_opversion opversion_operator__ai_onnx_ml__treeensembleregressor__3;
extern operator_set_opversion opversion_operator__ai_onnx_ml__treeensembleregressor__5;

operator_set_opname opname_operator__ai_onnx_ml__treeensembleregressor = {
    .name = "TreeEnsembleRegressor",
    .opversions = {
        &opversion_operator__ai_onnx_ml__treeensembleregressor__1,
        &opversion_operator__ai_onnx_ml__treeensembleregressor__3,
        &opversion_operator__ai_onnx_ml__treeensembleregressor__5,
        NULL
    }
};