//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorHeader.py
# ifndef OPERATOR_OPERATOR__AI_ONNX__CONSTANT__13_H
# define OPERATOR_OPERATOR__AI_ONNX__CONSTANT__13_H

# include "operators/operator.h"
# include "operators/operator_stub.h"
# include "operators/operator_info.h"

/**
 * ai.onnx operator 'Constant' version 13
 *
 * @param[in]  ctx  Operator context
 * @return          Status code
 *
 * This operator produces a constant tensor. Exactly one of the provided attributes, either value, sparse_value,
 * or value_* must be specified.
 * 
 * Constraint T:
 *   Constrain input and output types to all tensor types.
 *   Allowed Types: tensor_bfloat16, tensor_bool, tensor_complex128,
 *                  tensor_complex64, tensor_double, tensor_float,
 *                  tensor_float16, tensor_int16, tensor_int32, tensor_int64,
 *                  tensor_int8, tensor_string, tensor_uint16, tensor_uint32,
 *                  tensor_uint64, tensor_uint8

 * Output T output:
 *   Output tensor containing the same value of the provided tensor.
 *   Allowed Types: tensor_bfloat16, tensor_bool, tensor_complex128,
 *                  tensor_complex64, tensor_double, tensor_float,
 *                  tensor_float16, tensor_int16, tensor_int32, tensor_int64,
 *                  tensor_int8, tensor_string, tensor_uint16, tensor_uint32,
 *                  tensor_uint64, tensor_uint8
 * Attribute SPARSE_TENSOR sparse_value (optional):
 *   The value for the elements of the output tensor in sparse format.
 * 
 * Attribute TENSOR value (optional):
 *   The value for the elements of the output tensor.
 * 
 * Attribute FLOAT value_float (optional):
 *   The value for the sole element for the scalar, float32, output tensor.
 * 
 * Attribute FLOATS value_floats (optional):
 *   The values for the elements for the 1D, float32, output tensor.
 * 
 * Attribute INT value_int (optional):
 *   The value for the sole element for the scalar, int64, output tensor.
 * 
 * Attribute INTS value_ints (optional):
 *   The values for the elements for the 1D, int64, output tensor.
 * 
 * Attribute STRING value_string (optional):
 *   The value for the sole element for the scalar, UTF-8 string, output
 *   tensor.
 * 
 * Attribute STRINGS value_strings (optional):
 *   The values for the elements for the 1D, UTF-8 string, output tensor.
 *
 * @since version 13
 *
 * @see github/workspace/onnx/defs/generator/old.cc:457
 * @see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant
 */

operator_status
prepare_operator__ai_onnx__constant__13(
    node_context *ctx
);

extern operator_info info_operator__ai_onnx__constant__13;

typedef struct {
// no attributes
} context_operator__ai_onnx__constant__13;

operator_executer
resolve_operator__ai_onnx__constant__13(
    node_context *ctx
);

operator_status
execute_operator__ai_onnx__constant__13(
    node_context *ctx
);

# endif