//this file was generated by ../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opversion opversion_operator__ai_onnx__optionalhaselement__15;
extern operator_set_opversion opversion_operator__ai_onnx__optionalhaselement__18;

operator_set_opname opname_operator__ai_onnx__optionalhaselement = {
    .name = "OptionalHasElement",
    .opversions = {
        &opversion_operator__ai_onnx__optionalhaselement__15,
        &opversion_operator__ai_onnx__optionalhaselement__18,
        NULL
    }
};