//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__quantizelinear__19.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__quantizelinear__19__T1_tensor_int32__T2_tensor_tensor(float8e5m2)(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_x = searchInputByName(ctx, 0);
    // Onnx__TensorProto *i_y_scale = searchInputByName(ctx, 1);
    // Onnx__TensorProto *i_y_zero_point = searchInputByName(ctx, 2);

    // TRACE_TENSOR(2, true, i_x);
    // TRACE_TENSOR(2, true, i_y_scale);
    // TRACE_TENSOR(2, y_zero_point, i_y_zero_point);

    // context_operator__ai_onnx__quantizelinear__19 *op_ctx = ctx->executer_context;

    

    TRACE_VAR(2, true, axis, "%" PRId64);
    TRACE_VAR(2, true, saturate, "%" PRId64);

    // Onnx__TensorProto *o_y = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_y);

    /* DO CALCULATION HERE */


    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS EXECUTER IS VALID */
    return OP_ENOSYS;
    // return OP_OK;
}