//this file was generated by ../../../../../../../../connx/connx_ajit/scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__clip__6.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__clip__6(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    // Onnx__TensorProto *i_input = searchInputByName(ctx, 0);

    // TRACE_TENSOR(2, true, i_input);

    // Onnx__AttributeProto *a_max = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"max");
    // Onnx__AttributeProto *a_min = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"min");

    // TRACE_ATTRIBUTE(2, a_max, a_max);
    // TRACE_ATTRIBUTE(2, a_min, a_min);

    // Onnx__TensorProto *o_output = searchOutputByName(ctx, 0);

    // TRACE_TENSOR(2, true, o_output);

    /* FREE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__clip__6 *op_ctx = ctx->executer_context;

    TRACE_VAR(2, true, op_ctx->max, "%f");
    TRACE_VAR(2, true, op_ctx->min, "%f");

    

    // free(op_ctx);


    /* FREE OUTPUT DATA_TYPE AND SHAPE HERE */
    /* DO NOT FREE THE TENSOR ITSELF */

    // freeTensorData(o_output);
    // free(o_output->dims);

    TRACE_EXIT(1);
}